spring:
  profiles:
    default: local
  application:
    name: Lobby Management
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  expiration-seconds: 3600

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

lobby-manager:
  code-generation-retries: 10
  user-cleanup-interval-ms: 1_800_000 # 30m
  lobby-cleanup-interval-ms: 30_000 # 30s
  heartbeat-timeout-seconds: 60
