spring:
  profiles:
    default: local
  application:
    name: Lobby Management
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  expiration-seconds: 3600

lobby-manager:
  code-generation-retries: 10
  cleanup-interval-ms: 30_000
  heartbeat-timeout-seconds: 60
